version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=savi-intranet
      - POSTGRES_PASSWORD=s@v1-1ntr@n3t
      - POSTGRES_DB=savi-intranet
    ports:
      - "5432:5432"
    networks:
      - intranet

  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    networks:
      - intranet
networks:
  intranet:
